### ISSUE TITLE
Inscrição

### ISSUE THREAD

**Issue by rafaelvicio** [suissa/Curso-JavaScript-Super-Sayajin#100]
E-mail: rafaelvicio@icloud.com
Telegram: rafaelvicio

**Comment by suissa** [comment]
@rafaelvicio o depósito de R$35 deve ser feito nessa conta e envie o comprovante aqui nessa mesma ISSUE, por favor. 
 
Caixa Economica 
ag 0385 
op 013 
c/p 44307-3 (poupança) 
 
Franciele Pereira 
cpf 049.982.649-31
