### ISSUE TITLE
to dentro

### ISSUE THREAD

**Issue by thymochenko** [suissa/Curso-JavaScript-Super-Sayajin#14]
no

**Comment by suissa** [comment]
@thymochenko O depósito de R$35 deve ser feito nessa conta e envie o comprovante aqui nessa mesma ISSUE, por favor.

Caixa Economica
ag 0385
op 013
c/p 44307-3 (poupança)

Franciele Pereira
cpf 049.982.649-31

**Comment by suissa** [comment]
Pelo jeito esse não vai fazer!
