### ISSUE TITLE
Curso Javascript SSJ

### ISSUE THREAD

**Issue by phellipeandrade** [suissa/Curso-JavaScript-Super-Sayajin#15]
OK

**Comment by suissa** [comment]
@phellipeandrade O depósito de R$35 deve ser feito nessa conta e envie o comprovante aqui nessa mesma ISSUE, por favor.

Caixa Economica
ag 0385
op 013
c/p 44307-3 (poupança)

Franciele Pereira
cpf 049.982.649-31

**Comment by phellipeandrade** [comment]
![comprovante-suissa](https://user-images.githubusercontent.com/12415350/27609142-47b9832c-5b60-11e7-9dde-0d81bf5b8220.jpg)
