### ISSUE TITLE
Até o fim

### ISSUE THREAD

**Issue by gustavocardoso** [suissa/Curso-JavaScript-Super-Sayajin#253]
Esse curso vai até o final ou depois que vc pegar a grana vai parar no meio como o Be Mean!?!?

**Comment by marcosribj** [comment]
é calote em geral mesmo, baita dum safado, não cumpre com o combinado, faznedo os outros de idiotas

**Comment by suissa** [comment]
Primeiramente que R$35 eh apenas para o primeiro módulo.

**Comment by gustavocardoso** [comment]
Mas com 35 de mais de 200 otários vc consegue uma boa grana e para o curso no meio de novo!!!!

**Comment by gustavocardoso** [comment]
Tú devia ser homem e honrar seus compromissos e não simplesmente expular quem reclama dos grupos e bloquear!!!!

**Comment by adeonir** [comment]
E quem pagou os 35 por esse curso novo? Vai receber o conteúdo completo do módulo?

**Comment by suissa** [comment]
@adeonir obvio que vai, esses caras que estao querendo ferver o kisuco, pode ficar sossegado que esses idiotas nao sabem de nada ;)
