### ISSUE TITLE
SOu um trouxa.

### ISSUE THREAD

**Issue by marcosribj** [suissa/Curso-JavaScript-Super-Sayajin#254]
E ai
Vai terminar essa merda aí por competência ou vai dar calote e dar block em geral?

**Comment by gustavocardoso** [comment]
Eu acho que vai seguir o padrão do calote e block!!!
Azar de quem tá pagando!

**Comment by lucianoajunior** [comment]
Puts, que sacanagem. Vim na maior moral pra ajudar no projeto por ter gostado da grade.
Como já dizia o pica-pau: fui tapeado!

**Comment by ricardobsilva** [comment]
UAHUAHAUHAUAAUAHHUAA

BOA!

**Comment by ricardobsilva** [comment]
BOA! haha

**Comment by suissa** [comment]
Vou terminar com certeza. :*

**Comment by gustavocardoso** [comment]
Ele vai dar calote e vai dar block tb na galera que reclamar!
E vai ficar deletando os comentários.
Tudo bem, a gente fica comentando outra vez!!!
