### ISSUE TITLE
Vai terminar essa merda aí por competência ou vai dar calote e dar block em geral?

### ISSUE THREAD

**Issue by marcosribj** [suissa/Curso-JavaScript-Super-Sayajin#255]
Vai terminar essa merda aí por competência ou vai dar calote e dar block em geral?

E AÍ SEU FILHO DA PUTA, TROUXA É TUA MÃE, AQUELA VADIA 
💃

**Comment by gustavocardoso** [comment]
Vai dar calote e vai sumir. Não é homem nem de discutir na internet, imagina ao vivo?
Deve chorar e pedir desculpinhas!!!!
