### ISSUE TITLE
Que história é essa de que é mutreta?

### ISSUE THREAD

**Issue by tauanlemos** [suissa/Curso-JavaScript-Super-Sayajin#272]
Tava pensando em fazer o curso, mas vi agora o pessoal falando que é mutreta, que o curso para no meio e que sua mãe é isso ou aquilo. Que história é essa mano, dá pra explicar melhor?

Valeu!

**Comment by andi-xd** [comment]
É verdade, tava pensando em fazer o curso também, mas fiquei na dúvida, tem como explicar essa confusão?

**Comment by abensur** [comment]
doidera memo

**Comment by suissa** [comment]
Esse primeiro módulo que custa R$35 ja tem a ementa e serao 2 meses de aula. Nao tem mutreta nenhuma, ateh pq eu vivo criando conteúdos gratuitos tb.

**Comment by tauanlemos** [comment]
Posso pagar metade no início e o resto quando terminar?

**Comment by suissa** [comment]
Pode sim, fazemos 20/20 entao blz?

**Comment by CesarBalzer** [comment]
nao tem nada de mutreta, o curso e otimo e nao conheço nenhum que parou na metade, ja fiz outros e recomendo. a vida pessoal dele nao interessa aos alunos creio eu, como professor nao deixa a desejar, pelo contrario ajuda pakas

**Comment by gustavonetosp** [comment]
Tem mutreta sim! Ele criou o Be Mean, arrecadou mais de 80.000,00 e o curso simplesmente parou. Ele nao terminou e ainda se acha no direito de ficar puto com quem cobra o curso dele. E eu, babaca que sou, alémde pagar pelo curso ainda fiz uma vinheta em vídeo pra ele, que foi de muito bom grado na época!!!!

E agora tem uma galera insatisfeita Galera essa que ele expulsou e bloqueou do grupo do facebook.

Isso é só a pontinha do iceberg!!!

Beijos de luz!

**Comment by gustavonetosp** [comment]
Ah, e ele já bloqueou meu user aqui. Por isso fiz outro e to comentando!
E lógico que ele vai bloquear esse tb!
Arregão!!!!

**Comment by gustavonetosp** [comment]
Cezar, então vc não pagou pelo Be MEan! Aposto!!!!

**Comment by CesarBalzer** [comment]
paguei sim gustavo, e pago quando for preciso, o curso dele foi de grande proveito no meu trabalho

**Comment by suissa** [comment]
P/ começar o Be mean teria apenas 40 horas, ele tem mais de 60.

**Comment by tauanlemos** [comment]
Pô mano, 35 / 2 é 17,50. não é 20 não mano. Quer cobrar juros?

**Comment by cotts** [comment]
Poxa, estava afim de fazer o curso, mas vi esta treta aqui... desanimei...
Qual a garantia que eu vou ter que o curso vai ser concluído?

@CesarBalzer, desculpe, mas eu cheguei aqui agora e tá esquisita a situação..

**Comment by suissa** [comment]
@tauanlemos vc quer fazer em 2x entao sim.

**Comment by suissa** [comment]
@cotts Entao vc espere ele sair FREE e OPEN e depois ve sem pagar nada, blz???

**Comment by cotts** [comment]
ok

**Comment by cotts** [comment]
mas então não faz sentido cobrar já que vai sair OPEN?

**Comment by suissa** [comment]
E muito provavelmente quem esta reclamando nunca precisou da minha ajuda como dezenas de alunos que SEMPRE ajudo gratuitamente. Minha meta de vida ainda é poder ensinar apenas gratuitamente tanto que todos os meus cursos e módulos sempre ficarao abertos.

Quem nao quiser colaborar nao é obrigado, podera ver o curso depois que fechar a meta. Simples né?

**Comment by suissa** [comment]
@cotts faz sim, se chama crowdfunding. Vc nao deve ter lido a proposta do curso né?

**Comment by lucastafarelbs** [comment]
Basicamente quem paga vê primeiro, tem uma atenção mais "premium" devido à quantidade de pessoas que estarão fazendo o curso ao  mesmo tempo e ajuda o cara a continuar sendo professor, por esse motivo faz sentido cobrar, hora que atinge a meta, fica open/free :)

**Comment by andersonFaro9** [comment]
Mutreta alguma...não existe isso...todos os cursos da webschool são sempre pensados pra comunidade...


Perder essa oportunidade do curso é vacilo

**Comment by tauanlemos** [comment]
Valeu mano, mas não vou querer. #pas

**Comment by suissa** [comment]
@tauanlemos blz.

**Comment by suissa** [comment]
ps: paz*
