### ISSUE TITLE
Transparência de Serviço

### ISSUE THREAD

**Issue by cotts** [suissa/Curso-JavaScript-Super-Sayajin#273]
Olha só pessoal... Eu não quero saber o que está acontecendo, eu fui pesquisar sobre o curso e vi esta issue, eu entendo o que é crowdfunding e tudo mais, porém sempre antes de gastar o meu dinheiro com qualquer coisa eu pesquiso, e existem métodos mais eficientes e transparentes de se fazer crowdfunding, como ferramentas para o tal, e me desculpe, mas um lugar onde vejo issues abertas em demasia, informações pessoais de pessoas expostas em comentários (CPF, conta bancária, nome) e comentários apagados, me desculpe, mas não consigo enxergar transparência nisso... 

E @suissa, favor atentar-se à regra de satisfação de um cliente, que como isso é uma coisa por mais que colaborativa, está sendo PAGA! Cliente satisfeito fala bem para 5, cliente insatisfeito fala mal para 10.

**Comment by suissa** [comment]
@cotts Eu acho que tem tanta trransparencia que tem esses dados abertos, se não fosse não os teria né. Mas como já lhe disse, você não precisa colaborar mesmo querendo ver o curso, basta que os oiutros façam isso por você que o curso sairá OPEN para todos, pois esse é meu intuito.

Criar conteúdos de qualidade PARA TODOS, quem colabora com esse curso esta colaborando COM A COMUNIDADE PARA QUE TODOS POSSAM TER AS MESMAS OPORTUNIDADES independentemente se você tem ou não dinheiro.

Então para você é apenas aguardar para ver. ;)
