### ISSUE TITLE
Curso-JavaScript-Super-Sayajin

### ISSUE THREAD

**Issue by diihfilipe** [suissa/Curso-JavaScript-Super-Sayajin#30]
Inscrevendo nessa treta.

**Comment by suissa** [comment]
QNT TEMPOO hehehehe

@diihfilipe O depósito de R$35 deve ser feito nessa conta e envie o comprovante aqui nessa mesma ISSUE, por favor.

Caixa Economica
ag 0385
op 013
c/p 44307-3 (poupança)

Franciele Pereira
cpf 049.982.649-31

**Comment by suissa** [comment]
@diihfilipe coloque seus dados de email, fb, twitter e telegram plizzzz

**Comment by diihfilipe** [comment]
Jaeh granudão...

**Comment by diihfilipe** [comment]
diihfilipe@gmail.com
https://www.facebook.com/diihfilipe
https://twitter.com/diihfilipe
telegram: @masterjapa
