### ISSUE TITLE
Incrição

### ISSUE THREAD

**Issue by hunsche** [suissa/Curso-JavaScript-Super-Sayajin#52]

**Comment by suissa** [comment]
Preciso dos seus dados do Telegram, email, fb e twitter por favorrrr.

@hunsche  o depósito de R$35 deve ser feito nessa conta e envie o comprovante aqui nessa mesma ISSUE, por favor.  
  
Caixa Economica  
ag 0385  
op 013  
c/p 44307-3 (poupança)  
  
Franciele Pereira
